### ISSUE TITLE
browser crashes after creation

### ISSUE THREAD

**Issue by test2a** [combustor/reddit-accounts-generator#8] opened 2022-04-04 16:52 UTC
line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=33963): Max retries exceeded with url: /session/ad17de70-be8f-4017-8acc-4beb1b1f6170/window/rect (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0e4c08f880>: Failed to establish a new connection: [Errno 111] Connection refused'))

is this only supposed to create accounts one by one ?

**Comment by test2a** [comment] 2022-04-04 16:53
@combustor can you tell me what license for this project would you like ? it would be very nice if we had one

**Comment by combustor** [comment] 2022-04-04 16:56
> is this only supposed to create accounts one by one ?

it's supposed to loop, don't know why this is happening (maybe a lot of requests) and I will try to find a fix



> @combustor can you tell me what license for this project would you like ? it would be very nice if we had one

I am none the wiser about licenses

**Comment by test2a** [comment] 2022-04-04 16:59
@combustor basically there is MIT which is "fuck it, do whatever you like" while AGPL is like "use this project in only AGPL and similar licensed projects only.

MIT code can be used in proprietary code while that is not possible in AGPL. they would have to give full source code if demanded by customer. 
its more like the philosophy of free software

**Comment by combustor** [comment] 2022-04-04 17:07
Which one would you suggest?

Also found out that the error is caused by a rate limiter

**Comment by test2a** [comment] 2022-04-04 17:18
i personally contribute to agpl code primarily. github helps in differentiating between licenses great

**Comment by combustor** [comment] 2022-04-04 20:51
> i personally contribute to agpl code primarily. github helps in differentiating between licenses great

AGPL sounds good then

**Comment by combustor** [comment] 2022-04-04 20:52
also this should be fixed by https://github.com/combustor/reddit-accounts-generator/commit/a834ca9f3154487f13468191749cdf10494bda18

**Closed as completed** 2022-04-04 20:53 UTC
Labels: bug
